project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::resource('conta','ContaController');

project/app/Conta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Conta extends Model
{
    //
    protected $fillable = ['nome','valor','data','descricao'];
}

project/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

project/app/Http/Controllers/ContaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $conta = Conta::orderBy('id','valor')->paginate(5);
        return view('conta.index', compact('conta'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('conta.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'nome' => 'required',
            'valor' => 'required',
        ]);
        Conta::create($request->all());
        return redirect()->route('conta.index')
                         ->with('success', 'Conta criada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $conta = Conta::find($id);
        return view('conta.show', compact('conta'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $conta = Conta::find($id);
        return view('conta.edit',compact('conta'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'nome'=>'required',
            'valor'=>'required',
        ]);
        Conta::find($id)->update($request->all());
        return redirect()->route('conta.index')
                         ->with('success', 'Conta atualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Conta::find($id)->delete();
        return redirect()->route('conta.index')
                         ->with('success','Conta deletada');
    }
}

project/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

project/resources/views/layouts/create.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <section class="content">
            <div class="col-md-8 col-md-offset-2">
                @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Ops</strong>Há algum problema!<br><br>
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if(Session::has('success'))
                    <div class="alert alert-info">
                        {{Session::get('success')}}
                    </div>
                @endif
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Add Conta</h3>
                        </div>
                        <div class="panel-body">
                            <div class="table-container">
                                <form action="{{route('conta.store')}}" role="form">
                                    {{csrf_field()}}
                                    <div class="row">
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="fomr-group">
                                                <input type="text" name="nome" id="nome_conta" class="form-control input-sm" placeholder="Nome da Conta">
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <input type="text" name="valor" id="valor_conta" class="form-control input-sm" placeholder="Valor da conta">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <textarea name="descricao" id="descricao_conta" class="form-control input-sm"></textarea>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <input type="submit" value="Save" class="btn btn-success btn-block">
                                            <a href="{{route('conta.index')}}" class="btn btn-info btn-block">Voltar</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
            </div>
        </section>
    </div>
@endsection

project/resources/views/layouts/default.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Controle Contas</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../public/css/style.css">
</head>
<body>
    <div class="container-fluid">
        @yield('content')
    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

project/resources/views/layouts/edit.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <section class="content">
            <div class="col-md-8 col-md-offset-2">
                @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Ops!</strong>Algo deu errado<br><br>
                    </div>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
            </div>
                @endif
                @if(Session::has('success'))
                    <div class="alert alert-info">
                        {{Session::get('success')}}
                    </div>
                @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Update conta: {{$conta->nome}}</h3>
                </div>
                <div class="panel-body">
                    <div class="table-container">
                        <form method="post" action="{{route('conta.update', $conta->id)}}" role="form">
                            {{csrf_field()}}
                            <input type="hidden" name="">
                            <div class="row">
                                <div class="col-xs-6 col-sm-6">
                                    <div class="form-group">
                                        <input type="text" name="nome" id="nome_conta" value="{{$conta->nome}}" class="form-control input-sm" placeholder="Nome da conta">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6">
                                    <div class="form-group">
                                        <input type="text" name="valor" id="valor_conta" value="{{$conta->valor}}" class="form-control input-sm">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <textarea name="descricao" id="descricao_conta" class="form-control input-sm" placeholder="Descrição conta">{{$conta->descricao}}</textarea>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <input type="submit" value="Update" class="btn btn-success btn-block">
                                    <a href="{{route('conta.index')}}" class="btn btn-info btn-block">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

project/resources/views/layouts/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <section class="content">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel-body">
                    <div class="pull-left">
                        <h3>Lista de contas</h3>
                    </div>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a href="{{route('conta.create')}}" class="btn btn-info">Add</a>
                        </div>
                    </div>
                    <div class="table-container">
                        <table id="mytable" class="table table-bordred table-striped">
                            <thead>
                                <th><input type="checkbox" name="" id="checkall"></th>
                                <th>Nome</th>
                                <th>Valor</th>
                                <th>Data</th>
                                <th>Descricao</th>
                                <th>View</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </thead>
                            <tbody>
                                @if($conta->count())
                                    @foreach($conta as $contas)
                                        <tr>
                                            <td><input type="checkbox" name="" id="checkthis"></td>
                                            <td>{{$contas->nome}}</td>
                                            <td>{{$contas->valor}}</td>
                                            <td>{{$contas->data}}</td>
                                            <td>{{$contas->descricao}}</td>
                                            <td>
                                                <a href="{{action('ContaController@show', $contas->id)}}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-eye-open"></span></a></td>
                                            <td>
                                                <a href="{{action('ContaController@edit', $contas->id)}}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></a>
                                            </td>
                                            <td>
                                                <form action="{{action('ContaController@destroy', $conta->id)}}" method="post">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button></form>

                                            </td>
                                        </tr>
                                    @endforeach
                                    @else
                                        <tr>
                                            <td colspan="7">Sem contas encontradas</td>
                                        </tr>
                                    @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        @endsection
    </div>

project/resources/views/layouts/show.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <section class="content">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{$conta->nome}}</h3>
                    </div>
                    <div class="panel-body">
                        <div class="table-container">
                            <div class="conta" style="text-align:center">
                                {{$conta->valor}}">
                            </div>
                            <div class="conta">
                                {{$conta->descricao}}
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <a href="{{route('conta.index')}}" class="btn btn-info btn-block">Voltar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection